apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: vue-ci-sample
  name: vue-ci-sample
  namespace: vue-ci-sample
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8999
      nodePort: 30889
  selector:
    app: kubesphere
    component: vue-ci-sample
    tier: frontend
  sessionAffinity: None
  type: NodePort
