apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: vue-sample
    tier: frontend
  name: vue-sample
  namespace: vue-sample
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: vue-sample
      tier: frontend
  template:
    metadata:
      labels:
        app: kubesphere
        component: vue-sample
        tier: frontend
    spec:
      containers:
        - env:
          - name: CACHE_IGNORE
            value: js|html
          - name: CACHE_PUBLIC_EXPIRATION
            value: 3d
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          imagePullPolicy: Always
          name: vue-sample
          ports:
            - containerPort: 8999
              protocol: TCP
          resources:
            limits:
              cpu: '8'
              memory: 16Gi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
